### ISSUE TITLE
roaringbitmap.c:551:5: error: implicit declaration of function 'AggCheckCallContext' [-Werror=implicit-function-declaration]

### ISSUE THREAD

**Issue by jackwang2** [zeromax007/gpdb-roaringbitmap#1]
I used your code with GP version 4.3.7.15, the registration of sql function for roaring bitmap operation is always failed.

I found the pgsql extern function of AggCheckCallContext is missing from C header file fmgr.h,
then I switched to the newest version of GP 5.0.0-beta.4, and all looks good.

Leave a note here to save the time for anyone who visits this looking for roaring bitmap in greenplum.

**Comment by zeromax007** [comment]
Hi Jack,

I haven't 4.3.7  environment. It‘s passed the tests in GP 4.3.13. 

It means 4.3.7 aggregation memory function is different. If you want let it run with 4.3.7, you can copy AggCheckCallContext  function codes from GP 5.

**Comment by jackwang2** [comment]
Thank you for the reply, I will try the latest release 4.3.15.0

By the way, I created a docker image with GP 5.0.0-beta.4 and packaged roaring bitmap inside, it's more convenient for evaluation.

https://hub.docker.com/r/jackwang2/docker-gpdb/

**Comment by zeromax007** [comment]
Great job.
By the way, Roaring used native CPU instruction set.  If your machines have different CPU, it must be rebuild, and I don't know what will happen with docker in different machines.

**Comment by jackwang2** [comment]
The docker image is based on CentOS 6.9, the roaring bitmap source code was compiled and the binary was placed to GP $libdir path while building the image. Per my testing, it looks good. I guess the docker may handle the different CPU issue.

Anyway, this docker image is just for evaluation for anyone who has no resource to setup a GP cluster.
