### ISSUE TITLE
rb_and_agg 计算同样的bitmap，却出现不同结果的问题

### ISSUE THREAD

**Issue by taliove** [zeromax007/gpdb-roaringbitmap#10]
Greenplum 版本：PostgreSQL 9.4.24 (Greenplum Database 6.2.1 build commit:d90ac1a1b983b913b3950430d4d9e47ee8827fd4) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Dec 12 2019 18:35:48

---

## 问题描述

有两个一样的脚本。其中一个脚本直接计算bitmap，另外一个脚本计算表内的bitmap。两个bitmap一致。但是使用 rb_and_agg 计算时，会出现不一样的结果。

脚本1：

```sql
select rb_to_array(rb_and_agg(bitmap))               as result,
       count(1)                                      as total,
       string_agg(rb_to_array(bitmap)::varchar, ',') as str
from (values (rb_build('{1,2,3}')), (rb_build('{2,3,4}'))) t(bitmap);
```

结果为：

| field | value |
| --- | --- |
| result | {2,3} |
| total |  2 |
| str | {1,2,3},{2,3,4} |

正常。注释掉`count(1) as total`与`string_agg(rb_to_array(bitmap)::varchar, ',') as str`后，执行均正常得到and_agg计算结果。

---

脚本2：

```sql
select rb_to_array(rb_and_agg(bitmap))               as result,
       string_agg(rb_to_array(bitmap)::varchar, ',') as str
from (select bitmap from t_tmp where id in (4, 5) order by id) a;
```
其中表`t_tmp`内容为：

| id | rb_to_array(bitmap) |
| --- | --- |
| 4 | {1,2,3}  |
| 5 | {2,3,4}  |

脚本2执行结果为：

| result | str |
| --- | --- |
| {2,3} | {1,2,3},{2,3,4}  |

此处正常。但是当把**脚本2**中的`string_agg(rb_to_array(bitmap)::varchar, ',') as str`注释后，将得到以下**不正确的结果**：

| result  |
| --- |
| {} |

### 附录

表创建语句：

```sql
CREATE TABLE t_tmp
(
    id     integer,
    bitmap roaringbitmap
);
INSERT INTO t_tmp SELECT 4, rb_build('{1,2,3}');
INSERT INTO t_tmp SELECT 5, rb_build('{2,3,4}');
```

**Comment by zeromax007** [comment]
确认bug，将在下个版本中修复。

**Comment by zeromax007** [comment]
Fixed.

**Comment by taliove** [comment]
已使用 0.2.66 版本。
发现并未修复该问题。
