### ISSUE TITLE
版本0.2.66，rb_and_agg 计算同样的bitmap，却出现不同结果的问题（已修复）

### ISSUE THREAD

**Issue by taliove** [zeromax007/gpdb-roaringbitmap#11]
由于上一个issue无法reopen，所以我新开一个了。
参考：
https://github.com/zeromax007/gpdb-roaringbitmap/issues/10#issue-588182196

**Comment by zeromax007** [comment]
我这里没有再重现问题了，请重新连接服务器或者重启服务器试试。

**Comment by taliove** [comment]
感谢您的回复。我会重启试试。

**Comment by taliove** [comment]
重启gp后，验证无问题。感谢大佬。
