### ISSUE TITLE
Greenplum6 不支持gpdb-roaringbitmap，版本不兼容

### ISSUE THREAD

**Issue by softdzx** [zeromax007/gpdb-roaringbitmap#4]
版本：Greenplum Database 6.0.0-beta.6 build dev 
安装异常：
![image](https://user-images.githubusercontent.com/5812900/62703071-e9722a00-ba1a-11e9-97e5-809c9b7c9353.png)

**Comment by zeromax007** [comment]
看上去是GREENPLUM 6数据类型有改变，我需要先研究一下 6的源代码。

**Comment by softdzx** [comment]
有修复支持Greenplum6的日期吗

**Comment by zeromax007** [comment]
有小伙伴gaoyao帮忙修复了这个问题，已进行合并，请clone最新的源码，此issue关闭。
