### ISSUE TITLE
make 出错，roaring.c new_type未初始化

### ISSUE THREAD

**Issue by xiao321** [zeromax007/gpdb-roaringbitmap#7]
make 的时候有错误提示，变量未初始化，赋值 0后，可以正常编译
![image](https://user-images.githubusercontent.com/6407725/67834000-2c770180-fb21-11e9-8847-54a6b248d790.png)

**Comment by zeromax007** [comment]
系统默认编译参数的问题。
修改Makefile文件，在第六行 roaringbitmap.o: override CFLAGS += -march=native -std=c11 -fPIC ，改为 
roaringbitmap.o: override CFLAGS += -march=native -std=c11 -fPIC -w
